CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624091419_UpdateUserIdToString') THEN
    ALTER TABLE "VitalSigns" DROP CONSTRAINT "FK_VitalSigns_Patients_PatientId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624091419_UpdateUserIdToString') THEN
    ALTER TABLE "VitalSigns" ALTER COLUMN "PatientId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624091419_UpdateUserIdToString') THEN
    ALTER TABLE "MedicalRecords" ALTER COLUMN "CreatedByUserId" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624091419_UpdateUserIdToString') THEN
    ALTER TABLE "MedicalDocuments" ALTER COLUMN "UploadedByUserId" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624091419_UpdateUserIdToString') THEN
    ALTER TABLE "AuditLogs" ALTER COLUMN "UserId" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624091419_UpdateUserIdToString') THEN
    ALTER TABLE "AiAnalyses" ALTER COLUMN "RequestedByUserId" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624091419_UpdateUserIdToString') THEN
    ALTER TABLE "AiAnalyses" ADD "IsReviewed" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624091419_UpdateUserIdToString') THEN
    ALTER TABLE "AiAnalyses" ADD "Status" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624091419_UpdateUserIdToString') THEN
    ALTER TABLE "VitalSigns" ADD CONSTRAINT "FK_VitalSigns_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260624091419_UpdateUserIdToString') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260624091419_UpdateUserIdToString', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260625035905_AddPatientFields') THEN
    ALTER TABLE "Patients" ADD "IdentificationType" character varying(50) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260625035905_AddPatientFields') THEN
    ALTER TABLE "Patients" ADD "IsActive" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260625035905_AddPatientFields') THEN
    ALTER TABLE "Patients" ADD "PatientType" character varying(50) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260625035905_AddPatientFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260625035905_AddPatientFields', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE TABLE "AuditLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" character varying(450) NOT NULL,
        "UserName" character varying(200) NOT NULL,
        "UserRole" character varying(100) NOT NULL,
        "Action" character varying(200) NOT NULL,
        "EntityName" character varying(100) NOT NULL,
        "EntityId" character varying(50) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE TABLE "Patients" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FullName" character varying(200) NOT NULL,
        "BirthDate" date NOT NULL,
        "Gender" character varying(20) NOT NULL,
        "PhoneNumber" character varying(20) NOT NULL,
        "IdentificationNumber" character varying(50) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Patients" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE TABLE "Appointments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PatientId" integer NOT NULL,
        "DoctorId" integer NOT NULL,
        "AppointmentDate" timestamp with time zone NOT NULL,
        "Status" character varying(30) NOT NULL,
        "Reason" character varying(500) NOT NULL,
        "Notes" character varying(2000),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE TABLE "Alerts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PatientId" integer NOT NULL,
        "AppointmentId" integer NOT NULL,
        "Title" character varying(300) NOT NULL,
        "Description" text NOT NULL,
        "Severity" character varying(20) NOT NULL,
        "IsResolved" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Alerts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Alerts_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Alerts_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE TABLE "MedicalDocuments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PatientId" integer NOT NULL,
        "AppointmentId" integer,
        "UploadedByUserId" integer NOT NULL,
        "FileName" character varying(300) NOT NULL,
        "FileType" character varying(50) NOT NULL,
        "FilePath" text NOT NULL,
        "ExtractedText" text,
        "UploadedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MedicalDocuments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MedicalDocuments_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id"),
        CONSTRAINT "FK_MedicalDocuments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE TABLE "MedicalRecords" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PatientId" integer NOT NULL,
        "AppointmentId" integer NOT NULL,
        "CreatedByUserId" integer NOT NULL,
        "DiagnosisInitial" character varying(500) NOT NULL,
        "Notes" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MedicalRecords" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MedicalRecords_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_MedicalRecords_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE TABLE "Symptoms" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AppointmentId" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Severity" character varying(20) NOT NULL,
        "StartedAt" date NOT NULL,
        "Notes" character varying(500),
        CONSTRAINT "PK_Symptoms" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Symptoms_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE TABLE "VitalSigns" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PatientId" integer NOT NULL,
        "AppointmentId" integer NOT NULL,
        "Temperature" numeric(5,2) NOT NULL,
        "HeartRate" integer NOT NULL,
        "DiastolicPressure" integer NOT NULL,
        "SystolicPressure" integer NOT NULL,
        "OxygenSaturation" numeric(5,2) NOT NULL,
        "Glucose" numeric(6,2),
        "MeasuredAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_VitalSigns" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VitalSigns_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_VitalSigns_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE TABLE "AiAnalyses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PatientId" integer NOT NULL,
        "AppointmentId" integer NOT NULL,
        "DocumentId" integer,
        "RequestedByUserId" integer NOT NULL,
        "AnalysisType" character varying(100) NOT NULL,
        "PromptUsed" text NOT NULL,
        "AiResponse" text NOT NULL,
        "ModelUsed" character varying(100) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AiAnalyses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AiAnalyses_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_AiAnalyses_MedicalDocuments_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "MedicalDocuments" ("Id"),
        CONSTRAINT "FK_AiAnalyses_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE TABLE "Recommendations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AiAnalysisId" integer NOT NULL,
        "AppointmentId" integer NOT NULL,
        "Title" character varying(300) NOT NULL,
        "Description" text NOT NULL,
        "RiskLevel" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Recommendations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Recommendations_AiAnalyses_AiAnalysisId" FOREIGN KEY ("AiAnalysisId") REFERENCES "AiAnalyses" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Recommendations_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_AiAnalyses_AppointmentId" ON "AiAnalyses" ("AppointmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_AiAnalyses_DocumentId" ON "AiAnalyses" ("DocumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_AiAnalyses_PatientId" ON "AiAnalyses" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_Alerts_AppointmentId" ON "Alerts" ("AppointmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_Alerts_PatientId" ON "Alerts" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_Appointments_PatientId" ON "Appointments" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_MedicalDocuments_AppointmentId" ON "MedicalDocuments" ("AppointmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_MedicalDocuments_PatientId" ON "MedicalDocuments" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_MedicalRecords_AppointmentId" ON "MedicalRecords" ("AppointmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_MedicalRecords_PatientId" ON "MedicalRecords" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE UNIQUE INDEX "IX_Patients_IdentificationNumber" ON "Patients" ("IdentificationNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_Recommendations_AiAnalysisId" ON "Recommendations" ("AiAnalysisId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_Recommendations_AppointmentId" ON "Recommendations" ("AppointmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_Symptoms_AppointmentId" ON "Symptoms" ("AppointmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_VitalSigns_AppointmentId" ON "VitalSigns" ("AppointmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    CREATE INDEX "IX_VitalSigns_PatientId" ON "VitalSigns" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626174538_InitialPersistence') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260626174538_InitialPersistence', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "MedicalRecords" DROP CONSTRAINT "FK_MedicalRecords_Patients_PatientId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "VitalSigns" DROP CONSTRAINT "FK_VitalSigns_Patients_PatientId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "VitalSigns" ALTER COLUMN "PatientId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "Patients" ADD "IdentificationType" character varying(50) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "Patients" ADD "IsActive" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "Patients" ADD "PatientType" character varying(50) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "MedicalRecords" ALTER COLUMN "DiagnosisInitial" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "MedicalRecords" ALTER COLUMN "CreatedByUserId" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "MedicalDocuments" ALTER COLUMN "UploadedByUserId" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "Appointments" ALTER COLUMN "DoctorId" TYPE character varying(450);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "AiAnalyses" ALTER COLUMN "RequestedByUserId" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "AiAnalyses" ADD "IsReviewed" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "AiAnalyses" ADD "Status" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "MedicalRecords" ADD CONSTRAINT "FK_MedicalRecords_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    ALTER TABLE "VitalSigns" ADD CONSTRAINT "FK_VitalSigns_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628053440_FixAppointmentDoctorId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260628053440_FixAppointmentDoctorId', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628054549_AddMedicalRecordFields') THEN
    UPDATE "MedicalRecords" SET "DiagnosisInitial" = '' WHERE "DiagnosisInitial" IS NULL;
    ALTER TABLE "MedicalRecords" ALTER COLUMN "DiagnosisInitial" SET NOT NULL;
    ALTER TABLE "MedicalRecords" ALTER COLUMN "DiagnosisInitial" SET DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628054549_AddMedicalRecordFields') THEN
    ALTER TABLE "MedicalRecords" ADD "Antecedentes" character varying(1000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628054549_AddMedicalRecordFields') THEN
    ALTER TABLE "MedicalRecords" ADD "ObservacionesConsulta" character varying(1000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628054549_AddMedicalRecordFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260628054549_AddMedicalRecordFields', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628062906_FixAiAnalysisRequestedByUserId') THEN
    ALTER TABLE "AiAnalyses" ALTER COLUMN "RequestedByUserId" TYPE varchar(450) USING "RequestedByUserId"::text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260628062906_FixAiAnalysisRequestedByUserId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260628062906_FixAiAnalysisRequestedByUserId', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    DROP INDEX "IX_Patients_IdentificationNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "Patients" DROP COLUMN "FullName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "Patients" DROP COLUMN "IdentificationNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "MedicalRecords" DROP COLUMN "Antecedentes";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "MedicalRecords" DROP COLUMN "ObservacionesConsulta";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "VitalSigns" ALTER COLUMN "Temperature" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "VitalSigns" ALTER COLUMN "SystolicPressure" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "VitalSigns" ALTER COLUMN "OxygenSaturation" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "VitalSigns" ALTER COLUMN "MeasuredAt" TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "VitalSigns" ALTER COLUMN "HeartRate" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "VitalSigns" ALTER COLUMN "DiastolicPressure" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "VitalSigns" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "Recommendations" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "Patients" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "Patients" ADD "UserId" character varying(450) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "MedicalRecords" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "MedicalDocuments" ALTER COLUMN "UploadedAt" TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "AuditLogs" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "Appointments" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "Appointments" ALTER COLUMN "AppointmentDate" TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "Alerts" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    ALTER TABLE "AiAnalyses" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    CREATE UNIQUE INDEX "IX_Patients_UserId" ON "Patients" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260707173256_RefactorPatientRemoveDuplicateFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260707173256_RefactorPatientRemoveDuplicateFields', '10.0.9');
    END IF;
END $EF$;
COMMIT;

